nxp-ls20xx: add netcat-openbsd to whitelist for libvirt
Issue: LIN10-4644

When <bitbake core-image-base> with bsp nxp-ls20xx and nodistro setup,
error occurs as:
ERROR: Nothing RPROVIDES 'netcat-openbsd' (but .../libvirt_1.3.5.bb
RDEPENDS on or otherwise requires it)
......
Missing or unbuildable dependency chain was: ['core-image-base', 'dpdk', 'libvirt', 'netcat-openbsd']

To solve this issue, add netcat-openbsd to whitelist for libvirt in
bsp nxp-ls20xx layer.

Signed-off-by: Li Zhou <li.zhou@windriver.com>